name: Daily Buy Signal Check

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  check-signals:
    runs-on: self-hosted
    container: python:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r gemini/requirements.txt

      - name: Run signal check
        run: python gemini/check_signals.py
